# Generated by Django 2.2 on 2020-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200301_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectaccount',
            name='gender',
            field=models.CharField(choices=[('man', '男性'), ('woman', '女性')], max_length=200, verbose_name='性別'),
        ),
    ]
