# Generated by Django 2.2 on 2020-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200301_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectaccount',
            name='bank_code',
            field=models.IntegerField(max_length=20, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='branch_code',
            field=models.IntegerField(max_length=3, verbose_name='支店コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='phone_number',
            field=models.IntegerField(max_length=11, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='post_code',
            field=models.IntegerField(max_length=200, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='routing_number',
            field=models.IntegerField(max_length=20, verbose_name='account_number'),
        ),
    ]
