# Generated by Django 2.2 on 2020-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200301_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectaccount',
            name='address_kana',
            field=models.CharField(max_length=20, verbose_name='住所（かな）'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='address_kanji',
            field=models.CharField(max_length=20, verbose_name='住所（漢字）'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='gender',
            field=models.CharField(choices=[('man', '男性'), ('woman', '女性')], max_length=20, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='post_code',
            field=models.IntegerField(max_length=20, null=True, verbose_name='郵便番号'),
        ),
    ]
