# Generated by Django 2.2 on 2020-03-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200301_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectaccount',
            name='account_holder_name',
            field=models.CharField(max_length=20, null=True, verbose_name='名義人'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='account_number',
            field=models.CharField(max_length=20, null=True, verbose_name='account_number'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='bank_code',
            field=models.IntegerField(max_length=20, null=True, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='branch_code',
            field=models.IntegerField(max_length=3, null=True, verbose_name='支店コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='phone_number',
            field=models.IntegerField(max_length=11, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='routing_number',
            field=models.IntegerField(max_length=20, null=True, verbose_name='account_number'),
        ),
    ]
