# Generated by Django 2.2 on 2020-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200302_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectaccount',
            name='dob_day',
            field=models.IntegerField(max_length=20, null=True, verbose_name='誕生日（日）'),
        ),
        migrations.AddField(
            model_name='connectaccount',
            name='dob_month',
            field=models.IntegerField(max_length=20, null=True, verbose_name='誕生日（月）'),
        ),
        migrations.AddField(
            model_name='connectaccount',
            name='dob_year',
            field=models.IntegerField(max_length=20, null=True, verbose_name='誕生日（年）'),
        ),
    ]
