# Generated by Django 2.2 on 2020-03-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0013_auto_20200302_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectaccount',
            name='routing_number',
            field=models.IntegerField(max_length=20, null=True, verbose_name='routing_number'),
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custumer_id', models.CharField(max_length=200, verbose_name='CustumerID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
