# Generated by Django 2.2 on 2020-03-03 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_auto_20200303_0450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='custumer_id',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='account_number',
            field=models.IntegerField(null=True, verbose_name='口座番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='bank_code',
            field=models.IntegerField(null=True, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='branch_code',
            field=models.IntegerField(null=True, verbose_name='支店コード'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='dob_day',
            field=models.IntegerField(null=True, verbose_name='誕生日（日）'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='dob_month',
            field=models.IntegerField(null=True, verbose_name='誕生日（月）'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='dob_year',
            field=models.IntegerField(null=True, verbose_name='誕生日（年）'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='post_code',
            field=models.IntegerField(null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='connectaccount',
            name='routing_number',
            field=models.IntegerField(null=True, verbose_name='routing_number'),
        ),
    ]
