# Generated by Django 3.0 on 2019-12-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='ContactDetails',
        ),
    ]
