# Generated by Django 2.2 on 2020-01-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181201_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Message'),
        ),
    ]
