# Generated by Django 3.0 on 2019-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Nester',
            field=models.BooleanField(default=False, help_text='NESTER Designates whether the user can log into this admin site.', verbose_name='Nester'),
        ),
    ]
