# Generated by Django 3.0 on 2019-12-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20191223_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='homeProperty',
        ),
    ]
