# Generated by Django 3.0 on 2019-12-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20191219_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
