# Generated by Django 3.0 on 2020-01-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200102_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lastName',
            field=models.CharField(help_text='必須', max_length=50, null=True),
        ),
    ]
