# Generated by Django 2.2 on 2020-01-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20200103_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='houseType',
            field=models.CharField(choices=[('apartment', 'マンション・アパート'), ('isolated', '一軒家'), ('ur', 'UR住宅')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'あなたのもの'), ('rent', '借家')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='roomType',
            field=models.CharField(choices=[('simple', '部屋'), ('seperate', '離れ部屋')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableItems',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('tv', 'テレビ'), ('microwave', '電子レンジ'), ('airconditioner', 'エアコン'), ('desk', '机'), ('dryer', 'ヘヤドライヤー')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableSpace',
            field=models.CharField(choices=[('kitchan', 'キッチン'), ('washing', '洗濯機'), ('drying', '洗濯乾燥機'), ('garage', '駐車場'), ('other', 'その他')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='span',
            field=models.CharField(choices=[('short', '半年以下'), ('long', '半年以上'), ('verylong', '1年以上'), ('yet', 'まだわからない'), ('special', '特定期間')], max_length=10, null=True),
        ),
    ]
