# Generated by Django 2.2 on 2020-01-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_auto_20200114_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='submitStage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
