# Generated by Django 2.2 on 2020-01-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_auto_20200114_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to=settings.AUTH_USER_MODEL),
        ),
    ]
