# Generated by Django 2.2 on 2020-01-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_auto_20200115_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='houseType',
            field=models.CharField(choices=[('apartment', 'マンション・アパート'), ('isolated', '一軒家'), ('ur', 'UR住宅')], max_length=10, null=True, verbose_name='お家の種類*'),
        ),
        migrations.AddField(
            model_name='property',
            name='oneToOne',
            field=models.BooleanField(default=False, help_text='NESTER Designates whether the user can log into this admin site.', verbose_name='定員1名に独立した1部屋を提供できますか？？'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownerConfirm',
            field=models.NullBooleanField(verbose_name='物件所有者は登録者様ですか？？'),
        ),
        migrations.AddField(
            model_name='property',
            name='roomType',
            field=models.CharField(choices=[('simple', '部屋'), ('seperate', '離れ部屋')], max_length=10, null=True, verbose_name='お部屋のタイプ*'),
        ),
        migrations.AlterField(
            model_name='property',
            name='firstName',
            field=models.CharField(max_length=50, null=True, verbose_name='名*'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lastName',
            field=models.CharField(max_length=50, null=True, verbose_name='姓*'),
        ),
    ]
