# Generated by Django 2.2 on 2020-01-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_auto_20200115_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=40, verbose_name='町村番地'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathesNumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='お風呂の数を教えてください。'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=10, verbose_name='市区'),
        ),
        migrations.AddField(
            model_name='property',
            name='maxMenber',
            field=models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='ホームシェア可能な最大人数を教えてください。'),
        ),
        migrations.AddField(
            model_name='property',
            name='postCode',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='property',
            name='sharableItems',
            field=models.CharField(max_length=30, null=True, verbose_name='ホームシェア可能な最大人数を教えてください。'),
        ),
        migrations.AddField(
            model_name='property',
            name='sharableSpace',
            field=models.CharField(max_length=10, null=True, verbose_name='ホームシェア可能な最大人数を教えてください。'),
        ),
        migrations.AddField(
            model_name='property',
            name='toiletsNumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='トイレの数を教えてください。'),
        ),
        migrations.AlterField(
            model_name='property',
            name='oneToOne',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='定員1名に独立した1部屋を提供できますか？？'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownerConfirm',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='物件所有者は登録者様ですか？？'),
        ),
    ]
