# Generated by Django 2.2 on 2020-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0034_auto_20200115_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contextRoom',
            field=models.TextField(blank=True, help_text='何LDK，インテリア，近所にあるもの等', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contextStation',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contextSurrounding',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableSpace',
            field=models.CharField(max_length=10, null=True, verbose_name='ホームシェア可能なスペースを教えてください。'),
        ),
    ]
