# Generated by Django 2.2 on 2020-01-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_auto_20200116_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='家具付きですか？？'),
        ),
        migrations.AddField(
            model_name='property',
            name='member',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='現在の居住者'),
        ),
        migrations.AddField(
            model_name='property',
            name='memberUnder18',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='18歳以下'),
        ),
        migrations.AddField(
            model_name='property',
            name='petsType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ペットはいますか？？'),
        ),
    ]
