# Generated by Django 2.2 on 2020-01-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_auto_20200130_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='addtionalPrice',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='いいえの場合、メイトはいくら払う必要がありますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='年齢を教えてください*'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroomType',
            field=models.CharField(blank=True, max_length=40, verbose_name='メイトのバスルームタイプ'),
        ),
        migrations.AddField(
            model_name='property',
            name='collageName',
            field=models.CharField(blank=True, max_length=40, verbose_name='学校名'),
        ),
        migrations.AddField(
            model_name='property',
            name='companyName',
            field=models.CharField(blank=True, max_length=40, verbose_name='企業名'),
        ),
        migrations.AddField(
            model_name='property',
            name='contextEducation',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='研究、学んだこと、課題活動'),
        ),
        migrations.AddField(
            model_name='property',
            name='contextJob',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='どういうお仕事をされていましたか？？(されていますか？？)'),
        ),
        migrations.AddField(
            model_name='property',
            name='excludeMateType',
            field=models.CharField(max_length=10, null=True, verbose_name='受け入れることが好ましくないタイプのメイトはいますか？？'),
        ),
        migrations.AddField(
            model_name='property',
            name='facultyType',
            field=models.CharField(blank=True, max_length=40, verbose_name='学部、学科、専攻'),
        ),
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('man', '男性'), ('woman', '女性')], max_length=10, null=True, verbose_name='性別を教えてください*'),
        ),
        migrations.AddField(
            model_name='property',
            name='includeAdditionalFee',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='公共料金は含まれていますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='jobType',
            field=models.CharField(blank=True, max_length=40, verbose_name='役割'),
        ),
        migrations.AddField(
            model_name='property',
            name='memoRoomDetail',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='他に、特筆事項があれば、ご記入ください??'),
        ),
        migrations.AddField(
            model_name='property',
            name='petsPermission',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='ペットを許可しますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='profile',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='自己紹介を書いてみましょう！200文字以内'),
        ),
        migrations.AddField(
            model_name='property',
            name='rootine',
            field=models.CharField(blank=True, max_length=40, verbose_name='ルーティーン'),
        ),
        migrations.AddField(
            model_name='property',
            name='smokingPersiion',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='喫煙を許可しますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.TextField(blank=True, help_text='ホームシェア物件を探しているメイトが一番初めに見る見出しです。あなたのお家のユニークな点を35文字以内で書いてみましょう！', max_length=35, null=True, verbose_name='あなたのお家に、目に留まるようなタイトルをつけましょう！'),
        ),
        migrations.AddField(
            model_name='property',
            name='visiterPersiion',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='メイトの友達の招待を許可しますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='visiterStayPersiion',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='メイトの友達の宿泊を許可しますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='workingNow',
            field=models.NullBooleanField(choices=[('1', 'はい'), ('2', 'いいえ')], verbose_name='現在もお仕事されていますか??'),
        ),
        migrations.AddField(
            model_name='property',
            name='yourImage',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contextRoom',
            field=models.TextField(blank=True, help_text='何LDK，インテリア，近所にあるもの等', max_length=20, null=True, verbose_name='提供するお部屋を紹介してください'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contextStation',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='周辺の公共交通機関を教えてください'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contextSurrounding',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='お家やその周辺状況に関して、あなたの気に入っているところを紹介してみましょう'),
        ),
    ]
