# Generated by Django 2.2 on 2020-01-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_auto_20200130_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='共有スペース')),
            ],
        ),
        migrations.CreateModel(
            name='SharableSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='共有スペース')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='excludeMateType',
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableItems',
            field=models.ManyToManyField(to='property.SharableItem', verbose_name='共有物'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='sharableSpace',
        ),
        migrations.AddField(
            model_name='property',
            name='excludeMateType',
            field=models.ManyToManyField(to='property.ExcludeMate', verbose_name='共有スペース'),
        ),
        migrations.AddField(
            model_name='property',
            name='sharableSpace',
            field=models.ManyToManyField(to='property.SharableSpace', verbose_name='共有スペース'),
        ),
    ]
