# Generated by Django 2.2 on 2020-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_auto_20200131_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='excludeMateType',
            field=models.ManyToManyField(blank=True, to='property.ExcludeMate', verbose_name='好ましくないメイト'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableItems',
            field=models.ManyToManyField(blank=True, to='property.SharableItem', verbose_name='共有物'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharableSpace',
            field=models.ManyToManyField(blank=True, to='property.SharableSpace', verbose_name='共有スペース'),
        ),
    ]
