# Generated by Django 2.2 on 2020-02-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_auto_20200223_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furniture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='家具付きですか？'),
        ),
        migrations.AlterField(
            model_name='property',
            name='petsType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ペットはいますか？'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, help_text='ホームシェア物件を探しているメイトが一番初めに見る見出しです。あなたのお家のユニークな点を35文字以内で書いてみましょう！', max_length=35, null=True, verbose_name='あなたのお家に、目に留まるようなタイトルをつけましょう！'),
        ),
    ]
