# Generated by Django 2.2 on 2020-02-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_auto_20200223_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='addtionalPrice',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='いいえの場合、メイトはいくら払う必要がありますか?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='houseType',
            field=models.CharField(blank=True, choices=[('apartment', 'マンション・アパート'), ('isolated', '一軒家'), ('ur', 'UR住宅')], max_length=10, null=True, verbose_name='お家の種類*'),
        ),
        migrations.AlterField(
            model_name='property',
            name='includeAdditionalFee',
            field=models.NullBooleanField(choices=[(True, 'はい'), (False, 'いいえ')], verbose_name='公共料金は含まれていますか?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='maxMenber',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='ホームシェア可能な最大人数を教えてください。'),
        ),
        migrations.AlterField(
            model_name='property',
            name='memoRoomDetail',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='他に、特筆事項があれば、ご記入ください'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='家賃'),
        ),
        migrations.AlterField(
            model_name='property',
            name='roomType',
            field=models.CharField(blank=True, choices=[('simple', '部屋'), ('seperate', '離れ部屋')], max_length=10, null=True, verbose_name='お部屋のタイプ*'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visiterPersiion',
            field=models.NullBooleanField(choices=[(True, 'はい'), (False, 'いいえ')], verbose_name='メイトの友達の招待を許可しますか?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visiterStayPersiion',
            field=models.NullBooleanField(choices=[(True, 'はい'), (False, 'いいえ')], verbose_name='メイトの友達の宿泊を許可しますか?'),
        ),
    ]
