# Generated by Django 2.2 on 2020-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_auto_20200225_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='property/', verbose_name='お部屋の写真1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='jobType',
            field=models.CharField(blank=True, max_length=40, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='property',
            name='memberUnder18',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='18歳未満'),
        ),
    ]
