# Generated by Django 2.2 on 2020-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_auto_20200311_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='お部屋の写真2'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='お部屋の写真3'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='お部屋の写真4'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='お部屋の写真5'),
        ),
    ]
