# Generated by Django 2.2 on 2020-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0044_auto_20200311_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='property/', verbose_name='お部屋の写真1(必須)'),
        ),
    ]
